name: internal.yml
on:
  workflow_call:
    inputs:
        name:
            description: 'Name of the person to greet'
            required: false
            type: string
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: run-tests
        run: echo "run-tests" + "${{ inputs.name }}"
