name: internal.yml
on:
  workflow_call:
    inputs:
        name:
            description: 'Name of the person to greet'
            required: false
            type: string
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: run-tests
        run: echo "run-tests - ${{ inputs.name }}"

  validate-file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: validate-file
        run: node test.js

